name: dpp
description: 'A better dart pub publish. Before publish, runs tests, fixes, lint, updates CHANGELOG, pubspec file and git commands.'
version: 2.7.2
repository: https://github.com/insign/dart_dpp
executables:
  dpp:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2

dependencies:
  all_exit_codes: ^2.1.0
  args: ^2.4.2
  json2yaml: ^3.0.1
  path: ^1.9.0
  pub_semver: ^2.1.4
  yaml: ^3.1.2
  yaml2dart: ^1.5.1
